### ISSUE TITLE
Property '#private' in type 'SignerAgent' refers to a different member that cannot be accessed from within type 'SignerAgent'

### ISSUE THREAD

**Issue by baolongt** [slide-computer/signer-js#4]
I got this in my typescript project
```
Property '#private' in type 'SignerAgent' refers to a different member that cannot be accessed from within type 'SignerAgent'
```

context I defined this Agent type for two project both have same version of dependencies
```
import { HttpAgent } from "@dfinity/agent";
import { Signer } from "@slide-computer/signer";
import { SignerAgent } from "@slide-computer/signer-agent";

export type Agent = SignerAgent<Signer> | HttpAgent;
```

In constructor I init like this

project code 
```
import {Agent} from "type";
import MySDK from "MySDK";

// some class
constructor(agent: Agent){
   // Property '#private' in type 'SignerAgent' refers to a different member that cannot be accessed from within type 'SignerAgent'
   // vvvv 
  new MySDK(agent);
}

```

sdk code 

```
import {Agent} from "type";

// MySDK class
constructor(agent: Agent){
  this.agent=agent;
}
```
 `package.json`
 ```
    "@slide-computer/signer": "^3.6.4",
    "@slide-computer/signer-agent": "^3.6.4",
    "@dfinity/agent": "^2.1.2",
  ```

**Comment by sea-snake** [comment]
I indeed see the `#private` declared in the `d.ts` file. 

As you can see in the implementation of this repo `SignerAgent implements Agent`, so it should match the type constraints of `import { type Agent } from "@dfinity/agent"` (I'd recommend to use this type instead of the union type you declared above).

But the `#private` declaration might still cause above issue. I'll have a look on my end.

**Comment by baolongt** [comment]
Let me try with your suggestion

**Comment by sea-snake** [comment]
I tried to reproduce the error but couldn't find the issue.

Here's a link to a reproduction environment: https://codesandbox.io/p/sandbox/pjnstp

Feel free to fork it and make changes to see if you can reproduce the issue.

**Comment by baolongt** [comment]
I replaced the Agent to use `@dfinity/agent` and it works
